`timescale	1ps / 1ps
////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./main.v
// {{{
// Project:	KIMOS, a Mercury KX2 demonstration project
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga -I / -d -o . allclocks.txt clkcheck.txt global.txt crossbus.txt icape.txt version.txt pic.txt pwrcount.txt rtccount.txt spio.txt exconsole.txt wbuuart.txt wbuarbiter.txt bkram.txt flash.txt flashcfg.txt sdram.txt zipmaster.txt sdio.txt mem_flash_bkram.txt mem_sdram_only.txt mem_flash_sdram.txt mem_bkram_only.txt xdc.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2024, Gisselquist Technology, LLC
// {{{
// This file is part of the KIMOS project.
//
// The KIMOS project is free software and gateware: you can redistribute it
// and/or modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation, either version 3 of the License,
// or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory, run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
// }}}
// License:	GPL, v3, as defined and found on www.gnu.org,
// {{{
//		http://www.gnu.org/licenses/gpl.html
//
////////////////////////////////////////////////////////////////////////////////
//
// }}}
`default_nettype	none
////////////////////////////////////////////////////////////////////////////////
//
// Macro defines
// {{{
//
//
// Here is a list of defines which may be used, post auto-design
// (not post-build), to turn particular peripherals (and bus masters)
// on and off.  In particular, to turn off support for a particular
// design component, just comment out its respective `define below.
//
// These lines are taken from the respective @ACCESS tags for each of our
// components.  If a component doesn't have an @ACCESS tag, it will not
// be listed here.
//
// First, the independent access fields for any bus masters
`define	ALLCLOCKS_PRESENT
`define	WBUBUS_MASTER
// And then for the independent peripherals
`define	INCLUDE_ZIPCPU
`define	SDIO_ACCESS
`define	BKRAM_ACCESS
`define	FLASH_ACCESS
`define	BUSCONSOLE_ACCESS
`define	VERSION_ACCESS
`define	BUSPIC_ACCESS
`define	CFG_ACCESS
`define	PWRCOUNT_ACCESS
`define	SPIO_ACCESS
//
//
// The list of those things that have @DEPENDS tags
//
//
//
// Dependencies
// Any core with both an @ACCESS and a @DEPENDS tag will show up here.
// The @DEPENDS tag will turn into a series of ifdef's, with the @ACCESS
// being defined only if all of the ifdef's are true//
// Deplist for @$(PREFIX)=adcclk
`ifdef	ALLCLOCKS_PRESENT
`define	ADCCLK
`endif	// ALLCLOCKS_PRESENT
// Deplist for @$(PREFIX)=rxeth0ck
// Deplist for @$(PREFIX)=flashcfg
`ifdef	FLASH_ACCESS
`define	FLASHCFG_ACCESS
`endif	// FLASH_ACCESS
// Deplist for @$(PREFIX)=rxeth0ck
// Deplist for @$(PREFIX)=sdram
`ifdef	ALLCLOCKS_PRESENT
`define	SDRAM_ACCESS
`endif	// ALLCLOCKS_PRESENT
// Deplist for @$(PREFIX)=rxeth0ck
// Deplist for @$(PREFIX)=txclk
`ifdef	ALLCLOCKS_PRESENT
`define	TXCLK
`endif	// ALLCLOCKS_PRESENT
// Deplist for @$(PREFIX)=rxeth0ck
//
// The following macros have unmet dependencies.  They are listed
// here for reference, but their dependencies cannot be met.
// Unmet Dependency list for @$(PREFIX)=rxeth0ck
`ifdef	ETH0_ACCESS // This value is unknown
`define	RXETH0CK
`endif

//
// End of dependency list
//
//
// }}}
////////////////////////////////////////////////////////////////////////////////
//
// Any include files
// {{{
// These are drawn from anything with a MAIN.INCLUDE definition.
`include "builddate.v"
// }}}
//
// Finally, we define our main module itself.  We start with the list of
// I/O ports, or wires, passed into (or out of) the main function.
//
// These fields are copied verbatim from the respective I/O port lists,
// from the fields given by @MAIN.PORTLIST
//
module	main(i_clk, i_reset,
	// {{{
		// Veri1ator only interface
		cpu_sim_cyc,
		cpu_sim_stb,
		cpu_sim_we,
		cpu_sim_addr,
		cpu_sim_data,
		cpu_sim_stall,
		cpu_sim_ack,
		cpu_sim_idata,
`ifdef	VERILATOR
		cpu_prof_stb,
		cpu_prof_addr,
		cpu_prof_ticks,
`endif
		i_cpu_reset,
		// SDIO SD Card
		i_sdio_detect,
		//
		o_sdio_cfg_ddr,
		o_sdio_cfg_ds,
		o_sdio_cfg_dscmd,
		o_sdio_cfg_sample_shift,
		o_sdio_pp_cmd,
		o_sdio_pp_data,
		//
		o_sdio_sdclk,
		o_sdio_cmd_en,
		o_sdio_cmd_data,
		o_sdio_data_en,
		o_sdio_rx_en,
		o_sdio_tx_data,
		//
		i_sdio_cmd_strb,
		i_sdio_cmd_data,
		i_sdio_card_busy,
		i_sdio_rx_strb,
		i_sdio_rx_data,
		//
		i_sdio_ac_valid,
		i_sdio_ac_data,
		i_sdio_ad_valid,
		i_sdio_ad_data,
		i_sdio_debug,
		// SDRAM ports
		o_sdram_cyc, o_sdram_stb, o_sdram_we,
				o_sdram_addr, o_sdram_data, o_sdram_sel,
			i_sdram_stall, i_sdram_ack, i_sdram_data,
			i_sdram_err,
		// The Universal QSPI Flash
		o_qspi_cs_n, o_qspi_sck, o_qspi_dat, i_qspi_dat, o_qspi_mod,
		// Extra clocks
		i_clk_200mhz, i_clk_125mhz,
		// UART/host to wishbone interface
		i_wbu_uart_rx, o_wbu_uart_tx,
		// SPIO interface
		i_btn, o_led
	// }}}
	);
////////////////////////////////////////////////////////////////////////////////
//
// Any parameter definitions
// {{{
// These are drawn from anything with a MAIN.PARAM definition.
// As they aren't connected to the toplevel at all, it would
// be best to use localparam over parameter, but here we don't
// check
	////////////////////////////////////////////////////////////////////////
	//
	// Variables/definitions/parameters used by the ZipCPU bus master
	// {{{
	//
	// A 32-bit address indicating where the ZipCPU should start running
	// from
`ifdef	BKROM_ACCESS
	localparam	RESET_ADDRESS = @$(/bkrom.BASE);
`else
`ifdef	FLASH_ACCESS
	localparam	RESET_ADDRESS = 73400320;
`else
	localparam	RESET_ADDRESS = 167772160;
`endif	// FLASH_ACCESS
`endif	// BKROM_ACCESS
	//
	// The number of valid bits on the bus
	localparam	ZIP_ADDRESS_WIDTH = 25; // Zip-CPU address width
	//
	// Number of ZipCPU interrupts
	localparam	ZIP_INTS = 16;
	//
	// ZIP_START_HALTED
	//
	// A boolean, indicating whether or not the ZipCPU be halted on startup?
`ifdef	BKROM_ACCESS
	localparam	ZIP_START_HALTED=1'b0;
`else
	localparam	ZIP_START_HALTED=1'b1;
`endif
	// }}}
	////////////////////////////////////////////////////////////////////////
	//
	// WBUBUS parameters
	// {{{
	// Baudrate :   1000000
	// Clock    : 100000000
	localparam [23:0] BUSUART = 24'h64;	//   1000000 baud
	localparam	DBGBUSBITS = $clog2(BUSUART);
	// }}}
`ifndef	VERILATOR
	localparam	ICAPE_LGDIV=3;
`endif
// }}}
////////////////////////////////////////////////////////////////////////////////
//
// Port declarations
// {{{
// The next step is to declare all of the various ports that were just
// listed above.  
//
// The following declarations are taken from the values of the various
// @MAIN.IODECL keys.
//
	input	wire		i_clk;
	// verilator lint_off UNUSED
	input	wire		i_reset;
	// verilator lint_on UNUSED
	input	wire		cpu_sim_cyc, cpu_sim_stb;
	input	wire		cpu_sim_we;
	input	wire	[6:0]	cpu_sim_addr;
	input	wire	[31:0]	cpu_sim_data;
	//
	output	wire		cpu_sim_stall, cpu_sim_ack;
	output	wire	[31:0]	cpu_sim_idata;
	//
`ifdef	VERILATOR
	output	wire		cpu_prof_stb;
	output	wire	[25+$clog2(512/8)-1:0]	cpu_prof_addr;
	output	wire [31:0]	cpu_prof_ticks;
`endif
	input	wire		i_cpu_reset;
	// SDIO SD Card declarations
	// {{{
	input	wire		i_sdio_detect;
		//
	output	wire		o_sdio_cfg_ddr;
	output	wire		o_sdio_cfg_ds;
	output	wire		o_sdio_cfg_dscmd;
	output	wire	[4:0]	o_sdio_cfg_sample_shift;
	output	wire		o_sdio_pp_cmd;
	output	wire		o_sdio_pp_data;
		//
	output	wire	[7:0]	o_sdio_sdclk;
	output	wire		o_sdio_cmd_en;
	output	wire	[1:0]	o_sdio_cmd_data;
	output	wire		o_sdio_data_en;
	output	wire		o_sdio_rx_en;
	output	wire	[31:0]	o_sdio_tx_data;
		//
	input	wire	[1:0]	i_sdio_cmd_strb;
	input	wire	[1:0]	i_sdio_cmd_data;
	input	wire		i_sdio_card_busy;
	input	wire	[1:0]	i_sdio_rx_strb;
	input	wire	[15:0]	i_sdio_rx_data;
		//
	input	wire		i_sdio_ac_valid;
	input	wire	[1:0]	i_sdio_ac_data;
	input	wire		i_sdio_ad_valid;
	input	wire	[31:0]	i_sdio_ad_data;
	// Verilator lint_off UNUSED
	input	wire	[31:0]	i_sdio_debug;
	// Verilator lint_on  UNUSED
	// }}}
	// SDRAM I/O declarations
	// {{{
	output	wire			o_sdram_cyc,
					o_sdram_stb, o_sdram_we;
	output	wire	[24-1:0]	o_sdram_addr;
	output	wire	[(512-1):0]	o_sdram_data;
	output	wire	[(512/8)-1:0]	o_sdram_sel;
	//
	input	wire			i_sdram_ack;
	input	wire			i_sdram_stall;
	input	wire	[(512-1):0]	i_sdram_data;
	// Verilator lint_off UNUSED
	input	wire			i_sdram_err;
	// Verilator lint_on  UNUSED
	// }}}
	// The Universal QSPI flash
	output	wire		o_qspi_cs_n, o_qspi_sck;
	output	wire	[3:0]	o_qspi_dat;
	input	wire	[3:0]	i_qspi_dat;
	output	wire	[1:0]	o_qspi_mod;
	// Extra clocks
	// Verilator lint_off UNUSED
	input	wire		i_clk_200mhz, i_clk_125mhz; // i_clk_150mhz
	// Verilator lint_on  UNUSED
	input	wire		i_wbu_uart_rx;
	output	wire		o_wbu_uart_tx;
	// SPIO interface
	input	wire	[2-1:0]	i_btn;
	output	wire	[8-1:0]	o_led;
// }}}
	// Make Verilator happy
	// {{{
	// Defining bus wires for lots of components often ends up with unused
	// wires lying around.  We'll turn off Ver1lator's lint warning
	// here that checks for unused wires.
	// }}}
	// verilator lint_off UNUSED
	////////////////////////////////////////////////////////////////////////
	//
	// Declaring interrupt lines
	// {{{
	// These declarations come from the various components values
	// given under the @INT.<interrupt name>.WIRE key.
	//
	wire	zip_cpu_int;	// zip.INT.ZIP.WIRE
	wire	sdio_int;	// sdio.INT.SDCARD.WIRE
	wire	uartrxf_int;	// uart.INT.UARTRXF.WIRE
	wire	uarttx_int;	// uart.INT.UARTTX.WIRE
	wire	uarttxf_int;	// uart.INT.UARTTXF.WIRE
	wire	uartrx_int;	// uart.INT.UARTRX.WIRE
	wire	w_bus_int;	// buspic.INT.BUS.WIRE
	wire	spio_int;	// spio.INT.SPIO.WIRE
	// }}}
	////////////////////////////////////////////////////////////////////////
	//
	// Component declarations
	// {{{
	// These declarations come from the @MAIN.DEFNS keys found in the
	// various components comprising the design.
	//
	////////////////////////////////////////////////////////////////////////
	//
	// ZipSystem/ZipCPU connection definitions
	// {{{
`ifndef	VERILATOR
	wire		cpu_prof_stb;
	wire	[25+1:0]	cpu_prof_addr;
	wire [31:0]	cpu_prof_ticks;
`endif
	// All we define here is a set of scope wires
	// Verilator lint_off UNUSED
	wire		raw_cpu_dbg_stall, raw_cpu_dbg_ack;
	wire	[31:0]	zip_debug;
	wire		zip_trigger;
	// Verilator lint_on  UNUSED
	wire	[ZIP_INTS-1:0] zip_int_vector;
	// }}}
	// SDIO SD Card definitions
	// Verilator lint_off UNUSED
	wire		w_sdio_1p8v;
	wire	[31:0]	sdio_debug;
	assign		sdio_debug = i_sdio_debug;
	// Verilator lint_on  UNUSED
	// Definitions for the flash debug port
	// Verilator lint_off UNUSED
	wire		flash_dbg_trigger;
	wire	[31:0]	flash_debug;
	// Verilator lint_on  UNUSED
	// Verilator lint_off UNUSED
	reg		ck_pps;
	reg	[26:0]	ck_pps_counter;
	// Verilator lint_on  UNUSED
	// Verilator lint_off UNUSED
	reg	r_rxeth0ck_ack;
	// Verilator lint_on  UNUSED
	// Verilator lint_off UNUSED
	reg	r_txclk_ack;
	// Verilator lint_on  UNUSED
	// Verilator lint_off UNUSED
	wire	i_net_tx_clk;
	// Verilator lint_on  UNUSED
	// Verilator lint_off UNUSED
	reg	r_adcclk_ack;
	// Verilator lint_on  UNUSED
	////////////////////////////////////////////////////////////////////////
	//
	// WBUBUS: Console definitions
	// {{{
	wire		w_console_rx_stb, w_console_tx_stb, w_console_busy;
	wire	[6:0]	w_console_rx_data, w_console_tx_data;
	// Verilator lint_off UNUSED
	wire	[31:0]	uart_debug;
	// Verilator lint_on  UNUSED
	// }}}
	////////////////////////////////////////////////////////////////////////
	//
	// WBUBUS: USB-UART interface declarations
	// {{{
	//
	wire	[7:0]	wbu_rx_data, wbu_tx_data;
	wire		wbu_rx_stb;
	wire		wbu_tx_stb, wbu_tx_busy;

	// Verilator lint_off UNUSED
	wire	[0:0]	ex_reset;
	wire	[1:0]	ex_gpio;
	// Verilator lint_on  UNUSED
	// }}}
// BUILDTIME doesnt need to include builddate.v a second time
// `include "builddate.v"
	reg	[31:0]	r_pwrcount_data;
`ifndef	TIMESYNC
	reg	[31:0]	r_rtccount_data;
`endif
	wire	[8-1:0]	w_led;
	wire			w_sw;	// Since this design has no switches

// }}}
	////////////////////////////////////////////////////////////////////////
	//
	// Declaring interrupt vector wires
	// {{{
	// These declarations come from the various components having
	// PIC and PIC.MAX keys.
	//
	wire	[14:0]	sys_int_vector;
	wire	[14:0]	alt_int_vector;
	wire	[14:0]	bus_int_vector;
	// }}}
	////////////////////////////////////////////////////////////////////////
	//
	// Declare bus signals
	// {{{
	////////////////////////////////////////////////////////////////////////

	// Bus wbwide
	// {{{
	// Wishbone definitions for bus wbwide, component zip
	// Verilator lint_off UNUSED
	wire		wbwide_zip_cyc, wbwide_zip_stb, wbwide_zip_we;
	wire	[24:0]	wbwide_zip_addr;
	wire	[511:0]	wbwide_zip_data;
	wire	[63:0]	wbwide_zip_sel;
	wire		wbwide_zip_stall, wbwide_zip_ack, wbwide_zip_err;
	wire	[511:0]	wbwide_zip_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbwide, component wbu_arbiter
	// Verilator lint_off UNUSED
	wire		wbwide_wbu_arbiter_cyc, wbwide_wbu_arbiter_stb, wbwide_wbu_arbiter_we;
	wire	[24:0]	wbwide_wbu_arbiter_addr;
	wire	[511:0]	wbwide_wbu_arbiter_data;
	wire	[63:0]	wbwide_wbu_arbiter_sel;
	wire		wbwide_wbu_arbiter_stall, wbwide_wbu_arbiter_ack, wbwide_wbu_arbiter_err;
	wire	[511:0]	wbwide_wbu_arbiter_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbwide, component crossflash
	// Verilator lint_off UNUSED
	wire		wbwide_crossflash_cyc, wbwide_crossflash_stb, wbwide_crossflash_we;
	wire	[24:0]	wbwide_crossflash_addr;
	wire	[511:0]	wbwide_crossflash_data;
	wire	[63:0]	wbwide_crossflash_sel;
	wire		wbwide_crossflash_stall, wbwide_crossflash_ack, wbwide_crossflash_err;
	wire	[511:0]	wbwide_crossflash_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbwide, component crossbus
	// Verilator lint_off UNUSED
	wire		wbwide_crossbus_cyc, wbwide_crossbus_stb, wbwide_crossbus_we;
	wire	[24:0]	wbwide_crossbus_addr;
	wire	[511:0]	wbwide_crossbus_data;
	wire	[63:0]	wbwide_crossbus_sel;
	wire		wbwide_crossbus_stall, wbwide_crossbus_ack, wbwide_crossbus_err;
	wire	[511:0]	wbwide_crossbus_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbwide, component bkram
	// Verilator lint_off UNUSED
	wire		wbwide_bkram_cyc, wbwide_bkram_stb, wbwide_bkram_we;
	wire	[24:0]	wbwide_bkram_addr;
	wire	[511:0]	wbwide_bkram_data;
	wire	[63:0]	wbwide_bkram_sel;
	wire		wbwide_bkram_stall, wbwide_bkram_ack, wbwide_bkram_err;
	wire	[511:0]	wbwide_bkram_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbwide, component sdram
	// Verilator lint_off UNUSED
	wire		wbwide_sdram_cyc, wbwide_sdram_stb, wbwide_sdram_we;
	wire	[24:0]	wbwide_sdram_addr;
	wire	[511:0]	wbwide_sdram_data;
	wire	[63:0]	wbwide_sdram_sel;
	wire		wbwide_sdram_stall, wbwide_sdram_ack, wbwide_sdram_err;
	wire	[511:0]	wbwide_sdram_idata;
	// Verilator lint_on UNUSED
	// }}}
	// Bus wbu
	// {{{
	// Wishbone definitions for bus wbu, component wbu
	// Verilator lint_off UNUSED
	wire		wbu_cyc, wbu_stb, wbu_we;
	wire	[29:0]	wbu_addr;
	wire	[31:0]	wbu_data;
	wire	[3:0]	wbu_sel;
	wire		wbu_stall, wbu_ack, wbu_err;
	wire	[31:0]	wbu_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbu, component wbu_arbiter
	// Verilator lint_off UNUSED
	wire		wbu_wbu_arbiter_cyc, wbu_wbu_arbiter_stb, wbu_wbu_arbiter_we;
	wire	[29:0]	wbu_wbu_arbiter_addr;
	wire	[31:0]	wbu_wbu_arbiter_data;
	wire	[3:0]	wbu_wbu_arbiter_sel;
	wire		wbu_wbu_arbiter_stall, wbu_wbu_arbiter_ack, wbu_wbu_arbiter_err;
	wire	[31:0]	wbu_wbu_arbiter_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbu, component zip
	// Verilator lint_off UNUSED
	wire		wbu_zip_cyc, wbu_zip_stb, wbu_zip_we;
	wire	[29:0]	wbu_zip_addr;
	wire	[31:0]	wbu_zip_data;
	wire	[3:0]	wbu_zip_sel;
	wire		wbu_zip_stall, wbu_zip_ack, wbu_zip_err;
	wire	[31:0]	wbu_zip_idata;
	// Verilator lint_on UNUSED
	// }}}
	// Bus wbflash
	// {{{
	// Wishbone definitions for bus wbflash, component crossflash
	// Verilator lint_off UNUSED
	wire		wbflash_crossflash_cyc, wbflash_crossflash_stb, wbflash_crossflash_we;
	wire	[24:0]	wbflash_crossflash_addr;
	wire	[31:0]	wbflash_crossflash_data;
	wire	[3:0]	wbflash_crossflash_sel;
	wire		wbflash_crossflash_stall, wbflash_crossflash_ack, wbflash_crossflash_err;
	wire	[31:0]	wbflash_crossflash_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbflash, component sdio
	// Verilator lint_off UNUSED
	wire		wbflash_sdio_cyc, wbflash_sdio_stb, wbflash_sdio_we;
	wire	[24:0]	wbflash_sdio_addr;
	wire	[31:0]	wbflash_sdio_data;
	wire	[3:0]	wbflash_sdio_sel;
	wire		wbflash_sdio_stall, wbflash_sdio_ack, wbflash_sdio_err;
	wire	[31:0]	wbflash_sdio_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbflash, component flash
	// Verilator lint_off UNUSED
	wire		wbflash_flash_cyc, wbflash_flash_stb, wbflash_flash_we;
	wire	[24:0]	wbflash_flash_addr;
	wire	[31:0]	wbflash_flash_data;
	wire	[3:0]	wbflash_flash_sel;
	wire		wbflash_flash_stall, wbflash_flash_ack, wbflash_flash_err;
	wire	[31:0]	wbflash_flash_idata;
	// Verilator lint_on UNUSED
	// }}}
	// Bus wb32
	// {{{
	// Wishbone definitions for bus wb32, component crossbus
	// Verilator lint_off UNUSED
	wire		wb32_crossbus_cyc, wb32_crossbus_stb, wb32_crossbus_we;
	wire	[8:0]	wb32_crossbus_addr;
	wire	[31:0]	wb32_crossbus_data;
	wire	[3:0]	wb32_crossbus_sel;
	wire		wb32_crossbus_stall, wb32_crossbus_ack, wb32_crossbus_err;
	wire	[31:0]	wb32_crossbus_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32(SIO), component adcclk
	// Verilator lint_off UNUSED
	wire		wb32_adcclk_cyc, wb32_adcclk_stb, wb32_adcclk_we;
	wire	[8:0]	wb32_adcclk_addr;
	wire	[31:0]	wb32_adcclk_data;
	wire	[3:0]	wb32_adcclk_sel;
	wire		wb32_adcclk_stall, wb32_adcclk_ack, wb32_adcclk_err;
	wire	[31:0]	wb32_adcclk_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32(SIO), component buildtime
	// Verilator lint_off UNUSED
	wire		wb32_buildtime_cyc, wb32_buildtime_stb, wb32_buildtime_we;
	wire	[8:0]	wb32_buildtime_addr;
	wire	[31:0]	wb32_buildtime_data;
	wire	[3:0]	wb32_buildtime_sel;
	wire		wb32_buildtime_stall, wb32_buildtime_ack, wb32_buildtime_err;
	wire	[31:0]	wb32_buildtime_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32(SIO), component buspic
	// Verilator lint_off UNUSED
	wire		wb32_buspic_cyc, wb32_buspic_stb, wb32_buspic_we;
	wire	[8:0]	wb32_buspic_addr;
	wire	[31:0]	wb32_buspic_data;
	wire	[3:0]	wb32_buspic_sel;
	wire		wb32_buspic_stall, wb32_buspic_ack, wb32_buspic_err;
	wire	[31:0]	wb32_buspic_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32(SIO), component pwrcount
	// Verilator lint_off UNUSED
	wire		wb32_pwrcount_cyc, wb32_pwrcount_stb, wb32_pwrcount_we;
	wire	[8:0]	wb32_pwrcount_addr;
	wire	[31:0]	wb32_pwrcount_data;
	wire	[3:0]	wb32_pwrcount_sel;
	wire		wb32_pwrcount_stall, wb32_pwrcount_ack, wb32_pwrcount_err;
	wire	[31:0]	wb32_pwrcount_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32(SIO), component rtccount
	// Verilator lint_off UNUSED
	wire		wb32_rtccount_cyc, wb32_rtccount_stb, wb32_rtccount_we;
	wire	[8:0]	wb32_rtccount_addr;
	wire	[31:0]	wb32_rtccount_data;
	wire	[3:0]	wb32_rtccount_sel;
	wire		wb32_rtccount_stall, wb32_rtccount_ack, wb32_rtccount_err;
	wire	[31:0]	wb32_rtccount_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32(SIO), component rxeth0ck
	// Verilator lint_off UNUSED
	wire		wb32_rxeth0ck_cyc, wb32_rxeth0ck_stb, wb32_rxeth0ck_we;
	wire	[8:0]	wb32_rxeth0ck_addr;
	wire	[31:0]	wb32_rxeth0ck_data;
	wire	[3:0]	wb32_rxeth0ck_sel;
	wire		wb32_rxeth0ck_stall, wb32_rxeth0ck_ack, wb32_rxeth0ck_err;
	wire	[31:0]	wb32_rxeth0ck_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32(SIO), component spio
	// Verilator lint_off UNUSED
	wire		wb32_spio_cyc, wb32_spio_stb, wb32_spio_we;
	wire	[8:0]	wb32_spio_addr;
	wire	[31:0]	wb32_spio_data;
	wire	[3:0]	wb32_spio_sel;
	wire		wb32_spio_stall, wb32_spio_ack, wb32_spio_err;
	wire	[31:0]	wb32_spio_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32(SIO), component txclk
	// Verilator lint_off UNUSED
	wire		wb32_txclk_cyc, wb32_txclk_stb, wb32_txclk_we;
	wire	[8:0]	wb32_txclk_addr;
	wire	[31:0]	wb32_txclk_data;
	wire	[3:0]	wb32_txclk_sel;
	wire		wb32_txclk_stall, wb32_txclk_ack, wb32_txclk_err;
	wire	[31:0]	wb32_txclk_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32(SIO), component version
	// Verilator lint_off UNUSED
	wire		wb32_version_cyc, wb32_version_stb, wb32_version_we;
	wire	[8:0]	wb32_version_addr;
	wire	[31:0]	wb32_version_data;
	wire	[3:0]	wb32_version_sel;
	wire		wb32_version_stall, wb32_version_ack, wb32_version_err;
	wire	[31:0]	wb32_version_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32, component flashcfg
	// Verilator lint_off UNUSED
	wire		wb32_flashcfg_cyc, wb32_flashcfg_stb, wb32_flashcfg_we;
	wire	[8:0]	wb32_flashcfg_addr;
	wire	[31:0]	wb32_flashcfg_data;
	wire	[3:0]	wb32_flashcfg_sel;
	wire		wb32_flashcfg_stall, wb32_flashcfg_ack, wb32_flashcfg_err;
	wire	[31:0]	wb32_flashcfg_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32, component uart
	// Verilator lint_off UNUSED
	wire		wb32_uart_cyc, wb32_uart_stb, wb32_uart_we;
	wire	[8:0]	wb32_uart_addr;
	wire	[31:0]	wb32_uart_data;
	wire	[3:0]	wb32_uart_sel;
	wire		wb32_uart_stall, wb32_uart_ack, wb32_uart_err;
	wire	[31:0]	wb32_uart_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32, component wb32_sio
	// Verilator lint_off UNUSED
	wire		wb32_sio_cyc, wb32_sio_stb, wb32_sio_we;
	wire	[8:0]	wb32_sio_addr;
	wire	[31:0]	wb32_sio_data;
	wire	[3:0]	wb32_sio_sel;
	wire		wb32_sio_stall, wb32_sio_ack, wb32_sio_err;
	wire	[31:0]	wb32_sio_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb32, component cfg
	// Verilator lint_off UNUSED
	wire		wb32_cfg_cyc, wb32_cfg_stb, wb32_cfg_we;
	wire	[8:0]	wb32_cfg_addr;
	wire	[31:0]	wb32_cfg_data;
	wire	[3:0]	wb32_cfg_sel;
	wire		wb32_cfg_stall, wb32_cfg_ack, wb32_cfg_err;
	wire	[31:0]	wb32_cfg_idata;
	// Verilator lint_on UNUSED
	// }}}
	// }}}
	////////////////////////////////////////////////////////////////////////
	//
	// Peripheral address decoding, bus handling
	// {{{
	//
	// BUS-LOGIC for wbwide
	// {{{
	//
	// No class SINGLE peripherals on the "wbwide" bus
	//

	//
	// No class DOUBLE peripherals on the "wbwide" bus
	//

	// info: @ERROR.WIRE for crossflash matches the buses error name, wbwide_crossflash_err
	// info: @ERROR.WIRE for crossbus matches the buses error name, wbwide_crossbus_err
	assign	wbwide_bkram_err= 1'b0;
	assign	wbwide_sdram_err= 1'b0;
	//
	// Connect the wbwide bus components together using the wbxbar()
	//
	//
	wbxbar #(
		.NM(2), .NS(4), .AW(25), .DW(512),
		.SLAVE_ADDR({
			// Address width    = 25
			// Address LSBs     = 6
			// Slave name width = 10
			{ 25'h1000000 }, //      sdram: 0x40000000
			{ 25'h0280000 }, //      bkram: 0x0a000000
			{ 25'h0200000 }, //   crossbus: 0x08000000
			{ 25'h0000000 }  // crossflash: 0x00000000
		}),
		.SLAVE_MASK({
			// Address width    = 25
			// Address LSBs     = 6
			// Slave name width = 10
			{ 25'h1000000 }, //      sdram
			{ 25'h1f80000 }, //      bkram
			{ 25'h1f80000 }, //   crossbus
			{ 25'h1e00000 }  // crossflash
		}),
		.OPT_DBLBUFFER(1'b1))
	wbwide_xbar(
		.i_clk(i_clk), .i_reset(i_reset),
		.i_mcyc({
			wbwide_wbu_arbiter_cyc,
			wbwide_zip_cyc
		}),
		.i_mstb({
			wbwide_wbu_arbiter_stb,
			wbwide_zip_stb
		}),
		.i_mwe({
			wbwide_wbu_arbiter_we,
			wbwide_zip_we
		}),
		.i_maddr({
			wbwide_wbu_arbiter_addr,
			wbwide_zip_addr
		}),
		.i_mdata({
			wbwide_wbu_arbiter_data,
			wbwide_zip_data
		}),
		.i_msel({
			wbwide_wbu_arbiter_sel,
			wbwide_zip_sel
		}),
		.o_mstall({
			wbwide_wbu_arbiter_stall,
			wbwide_zip_stall
		}),
		.o_mack({
			wbwide_wbu_arbiter_ack,
			wbwide_zip_ack
		}),
		.o_mdata({
			wbwide_wbu_arbiter_idata,
			wbwide_zip_idata
		}),
		.o_merr({
			wbwide_wbu_arbiter_err,
			wbwide_zip_err
		}),
		// Slave connections
		.o_scyc({
			wbwide_sdram_cyc,
			wbwide_bkram_cyc,
			wbwide_crossbus_cyc,
			wbwide_crossflash_cyc
		}),
		.o_sstb({
			wbwide_sdram_stb,
			wbwide_bkram_stb,
			wbwide_crossbus_stb,
			wbwide_crossflash_stb
		}),
		.o_swe({
			wbwide_sdram_we,
			wbwide_bkram_we,
			wbwide_crossbus_we,
			wbwide_crossflash_we
		}),
		.o_saddr({
			wbwide_sdram_addr,
			wbwide_bkram_addr,
			wbwide_crossbus_addr,
			wbwide_crossflash_addr
		}),
		.o_sdata({
			wbwide_sdram_data,
			wbwide_bkram_data,
			wbwide_crossbus_data,
			wbwide_crossflash_data
		}),
		.o_ssel({
			wbwide_sdram_sel,
			wbwide_bkram_sel,
			wbwide_crossbus_sel,
			wbwide_crossflash_sel
		}),
		.i_sstall({
			wbwide_sdram_stall,
			wbwide_bkram_stall,
			wbwide_crossbus_stall,
			wbwide_crossflash_stall
		}),
		.i_sack({
			wbwide_sdram_ack,
			wbwide_bkram_ack,
			wbwide_crossbus_ack,
			wbwide_crossflash_ack
		}),
		.i_sdata({
			wbwide_sdram_idata,
			wbwide_bkram_idata,
			wbwide_crossbus_idata,
			wbwide_crossflash_idata
		}),
		.i_serr({
			wbwide_sdram_err,
			wbwide_bkram_err,
			wbwide_crossbus_err,
			wbwide_crossflash_err
		})
		);

	// End of bus logic for wbwide
	// }}}
	//
	// BUS-LOGIC for wbu
	// {{{
	//
	// No class SINGLE peripherals on the "wbu" bus
	//

	//
	// No class DOUBLE peripherals on the "wbu" bus
	//

	// info: @ERROR.WIRE for wbu_arbiter matches the buses error name, wbu_wbu_arbiter_err
	assign	wbu_zip_err= 1'b0;
	//
	// Connect the wbu bus components together using the wbxbar()
	//
	//
	wbxbar #(
		.NM(1), .NS(2), .AW(30), .DW(32),
		.SLAVE_ADDR({
			// Address width    = 30
			// Address LSBs     = 2
			// Slave name width = 11
			{ 30'h20000000 }, //         zip: 0x80000000
			{ 30'h00000000 }  // wbu_arbiter: 0x00000000
		}),
		.SLAVE_MASK({
			// Address width    = 30
			// Address LSBs     = 2
			// Slave name width = 11
			{ 30'h38000000 }, //         zip
			{ 30'h20000000 }  // wbu_arbiter
		}),
		.OPT_DBLBUFFER(1'b1))
	wbu_xbar(
		.i_clk(i_clk), .i_reset(i_reset),
		.i_mcyc({
			wbu_cyc
		}),
		.i_mstb({
			wbu_stb
		}),
		.i_mwe({
			wbu_we
		}),
		.i_maddr({
			wbu_addr
		}),
		.i_mdata({
			wbu_data
		}),
		.i_msel({
			wbu_sel
		}),
		.o_mstall({
			wbu_stall
		}),
		.o_mack({
			wbu_ack
		}),
		.o_mdata({
			wbu_idata
		}),
		.o_merr({
			wbu_err
		}),
		// Slave connections
		.o_scyc({
			wbu_zip_cyc,
			wbu_wbu_arbiter_cyc
		}),
		.o_sstb({
			wbu_zip_stb,
			wbu_wbu_arbiter_stb
		}),
		.o_swe({
			wbu_zip_we,
			wbu_wbu_arbiter_we
		}),
		.o_saddr({
			wbu_zip_addr,
			wbu_wbu_arbiter_addr
		}),
		.o_sdata({
			wbu_zip_data,
			wbu_wbu_arbiter_data
		}),
		.o_ssel({
			wbu_zip_sel,
			wbu_wbu_arbiter_sel
		}),
		.i_sstall({
			wbu_zip_stall,
			wbu_wbu_arbiter_stall
		}),
		.i_sack({
			wbu_zip_ack,
			wbu_wbu_arbiter_ack
		}),
		.i_sdata({
			wbu_zip_idata,
			wbu_wbu_arbiter_idata
		}),
		.i_serr({
			wbu_zip_err,
			wbu_wbu_arbiter_err
		})
		);

	// End of bus logic for wbu
	// }}}
	//
	// BUS-LOGIC for wbflash
	// {{{
	//
	// No class SINGLE peripherals on the "wbflash" bus
	//

	//
	// No class DOUBLE peripherals on the "wbflash" bus
	//

	assign	wbflash_sdio_err= 1'b0;
	assign	wbflash_flash_err= 1'b0;
	//
	// Connect the wbflash bus components together using the wbxbar()
	//
	//
	wbxbar #(
		.NM(1), .NS(2), .AW(25), .DW(32),
		.SLAVE_ADDR({
			// Address width    = 25
			// Address LSBs     = 2
			// Slave name width = 5
			{ 25'h1000000 }, // flash: 0x4000000
			{ 25'h0000000 }  //  sdio: 0x0000000
		}),
		.SLAVE_MASK({
			// Address width    = 25
			// Address LSBs     = 2
			// Slave name width = 5
			{ 25'h1000000 }, // flash
			{ 25'h1000000 }  //  sdio
		}),
		.OPT_DBLBUFFER(1'b1))
	wbflash_xbar(
		.i_clk(i_clk), .i_reset(i_reset),
		.i_mcyc({
			wbflash_crossflash_cyc
		}),
		.i_mstb({
			wbflash_crossflash_stb
		}),
		.i_mwe({
			wbflash_crossflash_we
		}),
		.i_maddr({
			wbflash_crossflash_addr
		}),
		.i_mdata({
			wbflash_crossflash_data
		}),
		.i_msel({
			wbflash_crossflash_sel
		}),
		.o_mstall({
			wbflash_crossflash_stall
		}),
		.o_mack({
			wbflash_crossflash_ack
		}),
		.o_mdata({
			wbflash_crossflash_idata
		}),
		.o_merr({
			wbflash_crossflash_err
		}),
		// Slave connections
		.o_scyc({
			wbflash_flash_cyc,
			wbflash_sdio_cyc
		}),
		.o_sstb({
			wbflash_flash_stb,
			wbflash_sdio_stb
		}),
		.o_swe({
			wbflash_flash_we,
			wbflash_sdio_we
		}),
		.o_saddr({
			wbflash_flash_addr,
			wbflash_sdio_addr
		}),
		.o_sdata({
			wbflash_flash_data,
			wbflash_sdio_data
		}),
		.o_ssel({
			wbflash_flash_sel,
			wbflash_sdio_sel
		}),
		.i_sstall({
			wbflash_flash_stall,
			wbflash_sdio_stall
		}),
		.i_sack({
			wbflash_flash_ack,
			wbflash_sdio_ack
		}),
		.i_sdata({
			wbflash_flash_idata,
			wbflash_sdio_idata
		}),
		.i_serr({
			wbflash_flash_err,
			wbflash_sdio_err
		})
		);

	// End of bus logic for wbflash
	// }}}
	//
	// BUS-LOGIC for wb32
	// {{{
	//
	// wb32 Bus logic to handle SINGLE slaves
	//
	reg		r_wb32_sio_ack;
	reg	[31:0]	r_wb32_sio_data;

	assign	wb32_sio_stall = 1'b0;

	initial r_wb32_sio_ack = 1'b0;
	always	@(posedge i_clk)
		r_wb32_sio_ack <= (wb32_sio_stb);
	assign	wb32_sio_ack = r_wb32_sio_ack;

	always	@(posedge i_clk)
	casez( wb32_sio_addr[3:0] )
	4'h0: r_wb32_sio_data <= wb32_adcclk_idata;
	4'h1: r_wb32_sio_data <= wb32_buildtime_idata;
	4'h2: r_wb32_sio_data <= wb32_buspic_idata;
	4'h3: r_wb32_sio_data <= wb32_pwrcount_idata;
	4'h4: r_wb32_sio_data <= wb32_rtccount_idata;
	4'h5: r_wb32_sio_data <= wb32_rxeth0ck_idata;
	4'h6: r_wb32_sio_data <= wb32_spio_idata;
	4'h7: r_wb32_sio_data <= wb32_txclk_idata;
	4'h8: r_wb32_sio_data <= wb32_version_idata;
	default: r_wb32_sio_data <= wb32_version_idata;
	endcase
	assign	wb32_sio_idata = r_wb32_sio_data;


	//
	// Now to translate this logic to the various SIO slaves
	//
	// In this case, the SIO bus has the prefix wb32_sio
	// and all of the slaves have various wires beginning
	// with their own respective bus prefixes.
	// Our goal here is to make certain that all of
	// the slave bus inputs match the SIO bus wires
	assign	wb32_adcclk_cyc = wb32_sio_cyc;
	assign	wb32_adcclk_stb = wb32_sio_stb && (wb32_sio_addr[ 3: 0] ==  4'h0);  // 0x000
	assign	wb32_adcclk_we  = wb32_sio_we;
	assign	wb32_adcclk_data= wb32_sio_data;
	assign	wb32_adcclk_sel = wb32_sio_sel;
	assign	wb32_buildtime_cyc = wb32_sio_cyc;
	assign	wb32_buildtime_stb = wb32_sio_stb && (wb32_sio_addr[ 3: 0] ==  4'h1);  // 0x004
	assign	wb32_buildtime_we  = wb32_sio_we;
	assign	wb32_buildtime_data= wb32_sio_data;
	assign	wb32_buildtime_sel = wb32_sio_sel;
	assign	wb32_buspic_cyc = wb32_sio_cyc;
	assign	wb32_buspic_stb = wb32_sio_stb && (wb32_sio_addr[ 3: 0] ==  4'h2);  // 0x008
	assign	wb32_buspic_we  = wb32_sio_we;
	assign	wb32_buspic_data= wb32_sio_data;
	assign	wb32_buspic_sel = wb32_sio_sel;
	assign	wb32_pwrcount_cyc = wb32_sio_cyc;
	assign	wb32_pwrcount_stb = wb32_sio_stb && (wb32_sio_addr[ 3: 0] ==  4'h3);  // 0x00c
	assign	wb32_pwrcount_we  = wb32_sio_we;
	assign	wb32_pwrcount_data= wb32_sio_data;
	assign	wb32_pwrcount_sel = wb32_sio_sel;
	assign	wb32_rtccount_cyc = wb32_sio_cyc;
	assign	wb32_rtccount_stb = wb32_sio_stb && (wb32_sio_addr[ 3: 0] ==  4'h4);  // 0x010
	assign	wb32_rtccount_we  = wb32_sio_we;
	assign	wb32_rtccount_data= wb32_sio_data;
	assign	wb32_rtccount_sel = wb32_sio_sel;
	assign	wb32_rxeth0ck_cyc = wb32_sio_cyc;
	assign	wb32_rxeth0ck_stb = wb32_sio_stb && (wb32_sio_addr[ 3: 0] ==  4'h5);  // 0x014
	assign	wb32_rxeth0ck_we  = wb32_sio_we;
	assign	wb32_rxeth0ck_data= wb32_sio_data;
	assign	wb32_rxeth0ck_sel = wb32_sio_sel;
	assign	wb32_spio_cyc = wb32_sio_cyc;
	assign	wb32_spio_stb = wb32_sio_stb && (wb32_sio_addr[ 3: 0] ==  4'h6);  // 0x018
	assign	wb32_spio_we  = wb32_sio_we;
	assign	wb32_spio_data= wb32_sio_data;
	assign	wb32_spio_sel = wb32_sio_sel;
	assign	wb32_txclk_cyc = wb32_sio_cyc;
	assign	wb32_txclk_stb = wb32_sio_stb && (wb32_sio_addr[ 3: 0] ==  4'h7);  // 0x01c
	assign	wb32_txclk_we  = wb32_sio_we;
	assign	wb32_txclk_data= wb32_sio_data;
	assign	wb32_txclk_sel = wb32_sio_sel;
	assign	wb32_version_cyc = wb32_sio_cyc;
	assign	wb32_version_stb = wb32_sio_stb && (wb32_sio_addr[ 3: 0] ==  4'h8);  // 0x020
	assign	wb32_version_we  = wb32_sio_we;
	assign	wb32_version_data= wb32_sio_data;
	assign	wb32_version_sel = wb32_sio_sel;
	//
	// No class DOUBLE peripherals on the "wb32" bus
	//

	assign	wb32_flashcfg_err= 1'b0;
	assign	wb32_uart_err= 1'b0;
	assign	wb32_sio_err= 1'b0;
	assign	wb32_cfg_err= 1'b0;
	//
	// Connect the wb32 bus components together using the wbxbar()
	//
	//
	wbxbar #(
		.NM(1), .NS(4), .AW(9), .DW(32),
		.SLAVE_ADDR({
			// Address width    = 9
			// Address LSBs     = 2
			// Slave name width = 8
			{ 9'h1c0 }, //      cfg: 0x700
			{ 9'h180 }, // wb32_sio: 0x600
			{ 9'h140 }, //     uart: 0x500
			{ 9'h100 }  // flashcfg: 0x400
		}),
		.SLAVE_MASK({
			// Address width    = 9
			// Address LSBs     = 2
			// Slave name width = 8
			{ 9'h1c0 }, //      cfg
			{ 9'h1c0 }, // wb32_sio
			{ 9'h1c0 }, //     uart
			{ 9'h1c0 }  // flashcfg
		}),
		.OPT_DBLBUFFER(1'b1))
	wb32_xbar(
		.i_clk(i_clk), .i_reset(i_reset),
		.i_mcyc({
			wb32_crossbus_cyc
		}),
		.i_mstb({
			wb32_crossbus_stb
		}),
		.i_mwe({
			wb32_crossbus_we
		}),
		.i_maddr({
			wb32_crossbus_addr
		}),
		.i_mdata({
			wb32_crossbus_data
		}),
		.i_msel({
			wb32_crossbus_sel
		}),
		.o_mstall({
			wb32_crossbus_stall
		}),
		.o_mack({
			wb32_crossbus_ack
		}),
		.o_mdata({
			wb32_crossbus_idata
		}),
		.o_merr({
			wb32_crossbus_err
		}),
		// Slave connections
		.o_scyc({
			wb32_cfg_cyc,
			wb32_sio_cyc,
			wb32_uart_cyc,
			wb32_flashcfg_cyc
		}),
		.o_sstb({
			wb32_cfg_stb,
			wb32_sio_stb,
			wb32_uart_stb,
			wb32_flashcfg_stb
		}),
		.o_swe({
			wb32_cfg_we,
			wb32_sio_we,
			wb32_uart_we,
			wb32_flashcfg_we
		}),
		.o_saddr({
			wb32_cfg_addr,
			wb32_sio_addr,
			wb32_uart_addr,
			wb32_flashcfg_addr
		}),
		.o_sdata({
			wb32_cfg_data,
			wb32_sio_data,
			wb32_uart_data,
			wb32_flashcfg_data
		}),
		.o_ssel({
			wb32_cfg_sel,
			wb32_sio_sel,
			wb32_uart_sel,
			wb32_flashcfg_sel
		}),
		.i_sstall({
			wb32_cfg_stall,
			wb32_sio_stall,
			wb32_uart_stall,
			wb32_flashcfg_stall
		}),
		.i_sack({
			wb32_cfg_ack,
			wb32_sio_ack,
			wb32_uart_ack,
			wb32_flashcfg_ack
		}),
		.i_sdata({
			wb32_cfg_idata,
			wb32_sio_idata,
			wb32_uart_idata,
			wb32_flashcfg_idata
		}),
		.i_serr({
			wb32_cfg_err,
			wb32_sio_err,
			wb32_uart_err,
			wb32_flashcfg_err
		})
		);

	// End of bus logic for wb32
	// }}}
	// }}}
	////////////////////////////////////////////////////////////////////////
	//
	// Declare the interrupt busses
	// {{{
	// Interrupt busses are defined by anything with a @PIC tag.
	// The @PIC.BUS tag defines the name of the wire bus below,
	// while the @PIC.MAX tag determines the size of the bus width.
	//
	// For your peripheral to be assigned to this bus, it must have an
	// @INT.NAME.WIRE= tag to define the wire name of the interrupt line,
	// and an @INT.NAME.PIC= tag matching the @PIC.BUS tag of the bus
	// your interrupt will be assigned to.  If an @INT.NAME.ID tag also
	// exists, then your interrupt will be assigned to the position given
	// by the ID# in that tag.
	//
	assign	sys_int_vector = {
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		uarttxf_int,
		uartrxf_int,
		sdio_int,
		w_bus_int,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0
	};
	assign	alt_int_vector = {
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		uartrx_int,
		uarttx_int,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0
	};
	assign	bus_int_vector = {
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		spio_int
	};
	// }}}
	////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////
	//
	// @MAIN.INSERT and @MAIN.ALT
	// {{{
	////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////
	//
	//
	// Now we turn to defining all of the parts and pieces of what
	// each of the various peripherals does, and what logic it needs.
	//
	// This information comes from the @MAIN.INSERT and @MAIN.ALT tags.
	// If an @ACCESS tag is available, an ifdef is created to handle
	// having the access and not.  If the @ACCESS tag is `defined above
	// then the @MAIN.INSERT code is executed.  If not, the @MAIN.ALT
	// code is exeucted, together with any other cleanup settings that
	// might need to take place--such as returning zeros to the bus,
	// or making sure all of the various interrupt wires are set to
	// zero if the component is not included.
	//
`ifdef	INCLUDE_ZIPCPU
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	// The ZipCPU/ZipSystem BUS master
	// {{{
	//
	assign	zip_int_vector = { alt_int_vector[14:8], sys_int_vector[14:6] };
	zipsystem #(
		// {{{
		.RESET_ADDRESS(RESET_ADDRESS),
		.ADDRESS_WIDTH(ZIP_ADDRESS_WIDTH + $clog2(512/8)),
		.BUS_WIDTH(512),
		.OPT_LGICACHE(12),
		.OPT_LGDCACHE(12),
		.START_HALTED(ZIP_START_HALTED),
		.RESET_DURATION(20),
		.OPT_PIPELINED(1),
`ifdef	VERILATOR
		.OPT_PROFILER(1'b1),
`else
		.OPT_PROFILER(1'b0),
`endif
`ifdef	ZIPSCOPE_SCOPE
		.OPT_TRACE_PORT(1'b1),
`else
		.OPT_TRACE_PORT(1'b0),
`endif
		.OPT_DISTRIBUTED_REGS(1),
		.EXTERNAL_INTERRUPTS(ZIP_INTS)
		// }}}
	) swic(
		// {{{
		.i_clk(i_clk), .i_reset(i_reset || i_cpu_reset),
			// Zipsys wishbone interface
			.o_wb_cyc(wbwide_zip_cyc), .o_wb_stb(wbwide_zip_stb), .o_wb_we(wbwide_zip_we),
			.o_wb_addr(wbwide_zip_addr[25-1:0]),
			.o_wb_data(wbwide_zip_data), // 512 bits wide
			.o_wb_sel(wbwide_zip_sel),  // 512/8 bits wide
		.i_wb_stall(wbwide_zip_stall), .i_wb_ack(wbwide_zip_ack), .i_wb_data(wbwide_zip_idata), .i_wb_err(wbwide_zip_err),
			.i_ext_int(zip_int_vector), .o_ext_int(zip_cpu_int),
			// Debug wishbone interface
			.i_dbg_cyc(wbu_zip_cyc || cpu_sim_cyc),
			.i_dbg_stb(cpu_sim_cyc ? cpu_sim_stb : wbu_zip_stb),
			.i_dbg_we( cpu_sim_cyc ? cpu_sim_we  : wbu_zip_we),
			.i_dbg_addr(cpu_sim_cyc? cpu_sim_addr : wbu_zip_addr[6:0]),
			.i_dbg_data (cpu_sim_cyc? cpu_sim_data : wbu_zip_data),
			.i_dbg_sel  (cpu_sim_cyc? 4'hf : wbu_zip_sel),
			.o_dbg_stall(raw_cpu_dbg_stall),
			.o_dbg_ack  (raw_cpu_dbg_ack),
			.o_dbg_data (wbu_zip_idata),
			//
			.o_cpu_debug(zip_debug),
			.o_prof_stb(cpu_prof_stb),
			.o_prof_addr(cpu_prof_addr),
			.o_prof_ticks(cpu_prof_ticks)
		// }}}
	);
	assign	zip_trigger = zip_debug[31];

	assign	wbu_zip_stall =  cpu_sim_cyc || raw_cpu_dbg_stall;
	assign	wbu_zip_ack   = !cpu_sim_cyc && raw_cpu_dbg_ack;
	assign	cpu_sim_stall = !cpu_sim_cyc || raw_cpu_dbg_stall;
	assign	cpu_sim_ack   =  cpu_sim_cyc && raw_cpu_dbg_ack;
	assign	cpu_sim_idata = wbu_zip_idata;

	// Keep Verilator happy
	// {{{
	// Verilator lint_off UNUSED
	wire	zip_unused;
	assign	zip_unused = &{ 1'b0,
			alt_int_vector[7:0], sys_int_vector[5:0]};
	// Verilator lint_on  UNUSED
	// }}}
	// }}}
	// }}}
`else	// INCLUDE_ZIPCPU
	// {{{
	// Null bus master
	// {{{
	// }}}
	// Null bus slave
	// {{{

	//
	// In the case that there is no wbu_zip peripheral
	// responding on the wbu bus
	assign	wbu_zip_ack   = 1'b0;
	assign	wbu_zip_err   = (wbu_zip_stb);
	assign	wbu_zip_stall = 0;
	assign	wbu_zip_idata = 0;

	// }}}
	// Null interrupt definitions
	// {{{
	assign	zip_cpu_int = 1'b0;	// zip.INT.ZIP.WIRE
	// }}}
	// }}}
`endif	// INCLUDE_ZIPCPU

`ifdef	SDIO_ACCESS
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	// SDIO SD Card handling
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	//

	sdio #(
		// {{{
		.LGFIFO(10), .NUMIO(4),
		.MW(32),
		.OPT_SERDES(1'b0),
		.OPT_DDR(1'b1),
		.OPT_CARD_DETECT(1'b1),
		.OPT_EMMC(1'b0)
		// }}}
	) u_sdio(
		// {{{
		.i_clk(i_clk),
		.i_reset(i_reset),
		.i_wb_cyc(wbflash_sdio_cyc), .i_wb_stb(wbflash_sdio_stb), .i_wb_we(wbflash_sdio_we),
			.i_wb_addr(wbflash_sdio_addr[3-1:0]),
			.i_wb_data(wbflash_sdio_data), // 32 bits wide
			.i_wb_sel(wbflash_sdio_sel),  // 32/8 bits wide
		.o_wb_stall(wbflash_sdio_stall),.o_wb_ack(wbflash_sdio_ack), .o_wb_data(wbflash_sdio_idata),
		.i_card_detect(i_sdio_detect),
		.o_1p8v(w_sdio_1p8v),
		.o_int(sdio_int),
		//
		.o_cfg_ddr(o_sdio_cfg_ddr),
		.o_cfg_ds(o_sdio_cfg_ds),
		.o_cfg_dscmd(o_sdio_cfg_dscmd),
		.o_cfg_sample_shift(o_sdio_cfg_sample_shift),
		.o_pp_cmd(o_sdio_pp_cmd),
		.o_pp_data(o_sdio_pp_data),
		//
		.o_sdclk(   o_sdio_sdclk),
		.o_cmd_en(  o_sdio_cmd_en),
		.o_cmd_data(o_sdio_cmd_data),
		.o_data_en( o_sdio_data_en),
		.o_rx_en(   o_sdio_rx_en),
		.o_tx_data( o_sdio_tx_data),
		//
		.i_cmd_strb( i_sdio_cmd_strb),
		.i_cmd_data( i_sdio_cmd_data),
		.i_card_busy(i_sdio_card_busy),
		.i_rx_strb(  i_sdio_rx_strb),
		.i_rx_data(  i_sdio_rx_data),
		//
		.S_AC_VALID(i_sdio_ac_valid),
		.S_AC_DATA( i_sdio_ac_data),
		.S_AD_VALID(i_sdio_ad_valid),
		.S_AD_DATA( i_sdio_ad_data)
		// }}}
	);

	// }}}
	// }}}
`else	// SDIO_ACCESS
	// {{{
	// Null bus slave
	// {{{

	//
	// In the case that there is no wbflash_sdio peripheral
	// responding on the wbflash bus
	assign	wbflash_sdio_ack   = 1'b0;
	assign	wbflash_sdio_err   = (wbflash_sdio_stb);
	assign	wbflash_sdio_stall = 0;
	assign	wbflash_sdio_idata = 0;

	// }}}
	// Null interrupt definitions
	// {{{
	assign	sdio_int = 1'b0;	// sdio.INT.SDCARD.WIRE
	// }}}
	// }}}
`endif	// SDIO_ACCESS

`ifdef	SDRAM_ACCESS
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	// Export the sdram bus to the top level
	// {{{
	assign	o_sdram_cyc  = wbwide_sdram_cyc;
	assign	o_sdram_stb  =(wbwide_sdram_stb);
	assign	o_sdram_we   = wbwide_sdram_we;
	assign	o_sdram_addr = wbwide_sdram_addr[24-1:0];
	assign	o_sdram_data = wbwide_sdram_data;
	assign	o_sdram_sel  = wbwide_sdram_sel;
	assign	wbwide_sdram_ack   = i_sdram_ack;
	assign	wbwide_sdram_stall = i_sdram_stall;
	assign	wbwide_sdram_idata = i_sdram_data;
	// }}}
	// }}}
`else	// SDRAM_ACCESS
	// {{{
	// Null bus slave
	// {{{

	//
	// In the case that there is no wbwide_sdram peripheral
	// responding on the wbwide bus
	assign	wbwide_sdram_ack   = 1'b0;
	assign	wbwide_sdram_err   = (wbwide_sdram_stb);
	assign	wbwide_sdram_stall = 0;
	assign	wbwide_sdram_idata = 0;

	// }}}
	// }}}
`endif	// SDRAM_ACCESS

`ifdef	FLASHCFG_ACCESS
	// {{{
	// The Flash control interface is defined by the flash instantiation
	// hence we don't need to do anything to define it here.
	// }}}
`else	// FLASHCFG_ACCESS
	// {{{
	// Null bus slave
	// {{{

	//
	// In the case that there is no wb32_flashcfg peripheral
	// responding on the wb32 bus
	assign	wb32_flashcfg_ack   = 1'b0;
	assign	wb32_flashcfg_err   = (wb32_flashcfg_stb);
	assign	wb32_flashcfg_stall = 0;
	assign	wb32_flashcfg_idata = 0;

	// }}}
	// }}}
`endif	// FLASHCFG_ACCESS

	wbdown #(
		// {{{
		// Slave bus address width: 25
		// Slave address width    : 21
		// Master address width   : 25
		.ADDRESS_WIDTH(21+$clog2(512/8)),
		.WIDE_DW(512),
		.SMALL_DW(32),
		.OPT_LITTLE_ENDIAN(1'b0),
		.OPT_LOWLOGIC(1'b0)
		// }}}
	) u_crossflash (
		// {{{
		.i_clk(i_clk),
		.i_reset(i_reset),
		// Slave/incoming
		// {{{
		.i_wcyc(  wbwide_crossflash_cyc),
		.i_wstb(  wbwide_crossflash_stb),
		.i_wwe(   wbwide_crossflash_we),
		.i_waddr( wbwide_crossflash_addr[21-1:0]),
		.i_wdata( wbwide_crossflash_data),
		.i_wsel(  wbwide_crossflash_sel),
		.o_wstall(wbwide_crossflash_stall),
		.o_wack(  wbwide_crossflash_ack),
		.o_wdata( wbwide_crossflash_idata),
		.o_werr(  wbwide_crossflash_err),
		// }}}
		// Master/down-range/outgoing
		// {{{
		.o_scyc(  wbflash_crossflash_cyc),
		.o_sstb(  wbflash_crossflash_stb),
		.o_swe(   wbflash_crossflash_we),
		.o_saddr( wbflash_crossflash_addr[25-1:0]),
		.o_sdata( wbflash_crossflash_data),
		.o_ssel(  wbflash_crossflash_sel),
		.i_sstall(wbflash_crossflash_stall),
		.i_sack(  wbflash_crossflash_ack),
		.i_sdata( wbflash_crossflash_idata),
		.i_serr(  wbflash_crossflash_err)
		// }}}
		// }}}
	);
`ifdef	BKRAM_ACCESS
	// {{{
	memdev #(
		.LGMEMSZ(18),
		.DW(512),
		.EXTRACLOCK(1)
	) bkrami(
		.i_clk(i_clk),
		.i_reset(i_reset),
		.i_wb_cyc(wbwide_bkram_cyc), .i_wb_stb(wbwide_bkram_stb), .i_wb_we(wbwide_bkram_we),
			.i_wb_addr(wbwide_bkram_addr[12-1:0]),
			.i_wb_data(wbwide_bkram_data), // 512 bits wide
			.i_wb_sel(wbwide_bkram_sel),  // 512/8 bits wide
		.o_wb_stall(wbwide_bkram_stall),.o_wb_ack(wbwide_bkram_ack), .o_wb_data(wbwide_bkram_idata)
	);
	// }}}
`else	// BKRAM_ACCESS
	// {{{
	// Null bus slave
	// {{{

	//
	// In the case that there is no wbwide_bkram peripheral
	// responding on the wbwide bus
	assign	wbwide_bkram_ack   = 1'b0;
	assign	wbwide_bkram_err   = (wbwide_bkram_stb);
	assign	wbwide_bkram_stall = 0;
	assign	wbwide_bkram_idata = 0;

	// }}}
	// }}}
`endif	// BKRAM_ACCESS

`ifdef	FLASH_ACCESS
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	// Flash controller
	// {{{
	qflexpress #(
		// {{{
		.LGFLASHSZ(26), .OPT_CLKDIV(1),
		.OPT_ENDIANSWAP(0),
		.NDUMMY(6), .RDDELAY(1),
		.OPT_STARTUP_FILE("spansion.hex"),
`ifdef	FLASHCFG_ACCESS
		.OPT_CFG(1'b1)
`else
		.OPT_CFG(1'b0)
`endif
		// }}}
	) flashi(
		// {{{
		.i_clk(i_clk), .i_reset(i_reset),
		// Primary memory reading inputs
		.i_wb_cyc(wbflash_flash_cyc), .i_wb_stb(wbflash_flash_stb), .i_wb_we(wbflash_flash_we),
			.i_wb_addr(wbflash_flash_addr[24-1:0]),
			.i_wb_data(wbflash_flash_data), // 32 bits wide
			.i_wb_sel(wbflash_flash_sel),  // 32/8 bits wide
		.o_wb_stall(wbflash_flash_stall),.o_wb_ack(wbflash_flash_ack), .o_wb_data(wbflash_flash_idata),
		// Configuration bus ports
		.i_cfg_cyc(wb32_flashcfg_cyc), .i_cfg_stb(wb32_flashcfg_stb), .i_cfg_we(wb32_flashcfg_we),
			.i_cfg_data(wb32_flashcfg_data), // 32 bits wide
			.i_cfg_sel(wb32_flashcfg_sel),  // 32/8 bits wide
		.o_cfg_stall(wb32_flashcfg_stall),.o_cfg_ack(wb32_flashcfg_ack), .o_cfg_data(wb32_flashcfg_idata),
		.o_qspi_sck(o_qspi_sck), .o_qspi_cs_n(o_qspi_cs_n),
		.o_qspi_mod(o_qspi_mod), .o_qspi_dat(o_qspi_dat),
			.i_qspi_dat(i_qspi_dat),
		.o_dbg_trigger(flash_dbg_trigger), .o_debug(flash_debug)
		// }}}
	);
	// }}}
	// }}}
`else	// FLASH_ACCESS
	// {{{
	assign	o_qspi_sck  = 1'b1;
	assign	o_qspi_cs_n = 1'b1;
	assign	o_qspi_mod  = 2'b01;
	assign	o_qspi_dat  = 4'b1111;
	// Verilator lint_off UNUSED
	wire	flash_unused = &{ 1'b0, i_qspi_dat };
	// Verilator lint_on UNUSED
	// Null bus slave
	// {{{

	//
	// In the case that there is no wbflash_flash peripheral
	// responding on the wbflash bus
	assign	wbflash_flash_ack   = 1'b0;
	assign	wbflash_flash_err   = (wbflash_flash_stb);
	assign	wbflash_flash_stall = 0;
	assign	wbflash_flash_idata = 0;

	// }}}
	// }}}
`endif	// FLASH_ACCESS

	initial	ck_pps = 1'b0;
	initial	ck_pps_counter = 0;
	always @(posedge i_clk)
	if (ck_pps_counter > 0)
	begin
		ck_pps_counter <= ck_pps_counter - 1;
		ck_pps <= 1'b0;
	end else begin
		ck_pps_counter <= 27'd100_000_000 - 1;
		ck_pps <= 1'b1;
	end
`ifdef	RXETH0CK
	// {{{
	clkcounter #(
		.CLOCKFREQ_HZ(0)	// We'll count PPS externally
	) clkrxeth0ckctr(
		.i_sys_clk(i_clk),
		.i_tst_clk(i_eth0_rx_clk),
		.i_sys_pps(ck_pps),
		.o_sys_counts(wb32_rxeth0ck_idata)
	);

	always @(posedge i_clk)
		r_rxeth0ck_ack <= !i_reset && wb32_rxeth0ck_stb;
	assign	wb32_rxeth0ck_ack   = r_rxeth0ck_ack;
	assign	wb32_rxeth0ck_stall = 1'b0;
	// }}}
`else	// RXETH0CK
	// {{{
	assign	wb32_rxeth0ck_idata = 0;

	initial	r_rxeth0ck_ack = 1'b0;
	always @(*)
		r_rxeth0ck_ack = 1'b0;
	// }}}
`endif	// RXETH0CK

`ifdef	TXCLK
	// {{{
	clkcounter #(
		.CLOCKFREQ_HZ(0)	// We'll count PPS externally
	) clktxclkctr(
		.i_sys_clk(i_clk),
		.i_tst_clk(i_net_tx_clk),
		.i_sys_pps(ck_pps),
		.o_sys_counts(wb32_txclk_idata)
	);

	always @(posedge i_clk)
		r_txclk_ack <= !i_reset && wb32_txclk_stb;
	assign	wb32_txclk_ack   = r_txclk_ack;
	assign	wb32_txclk_stall = 1'b0;
	// }}}
`else	// TXCLK
	// {{{
	assign	wb32_txclk_idata = 0;

	initial	r_txclk_ack = 1'b0;
	always @(*)
		r_txclk_ack = 1'b0;
	// }}}
`endif	// TXCLK

	assign	i_net_tx_clk = i_clk_125mhz;
`ifdef	ADCCLK
	// {{{
	clkcounter #(
		.CLOCKFREQ_HZ(0)	// We'll count PPS externally
	) clkadcclkctr(
		.i_sys_clk(i_clk),
		.i_tst_clk(i_clk_200mhz),
		.i_sys_pps(ck_pps),
		.o_sys_counts(wb32_adcclk_idata)
	);

	always @(posedge i_clk)
		r_adcclk_ack <= !i_reset && wb32_adcclk_stb;
	assign	wb32_adcclk_ack   = r_adcclk_ack;
	assign	wb32_adcclk_stall = 1'b0;
	// }}}
`else	// ADCCLK
	// {{{
	assign	wb32_adcclk_idata = 0;

	initial	r_adcclk_ack = 1'b0;
	always @(*)
		r_adcclk_ack = 1'b0;
	// }}}
`endif	// ADCCLK

`ifdef	BUSCONSOLE_ACCESS
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	// WBUBUS: Console instantiations
	// {{{
	wbconsole #(.LGFLEN(6)
	) console(
		// {{{
		.i_clk(i_clk), .i_reset(1'b0),
		.i_wb_cyc(wb32_uart_cyc), .i_wb_stb(wb32_uart_stb), .i_wb_we(wb32_uart_we),
			.i_wb_addr(wb32_uart_addr[2-1:0]),
			.i_wb_data(wb32_uart_data), // 32 bits wide
			.i_wb_sel(wb32_uart_sel),  // 32/8 bits wide
		.o_wb_stall(wb32_uart_stall),.o_wb_ack(wb32_uart_ack), .o_wb_data(wb32_uart_idata),
		.o_uart_stb(w_console_tx_stb), .o_uart_data(w_console_tx_data),
			.i_uart_busy(w_console_busy),
		.i_uart_stb(w_console_rx_stb), .i_uart_data(w_console_rx_data),
		.o_uart_rx_int(uartrx_int), .o_uart_tx_int(uarttx_int),
			.o_uart_rxfifo_int(uartrxf_int),
			.o_uart_txfifo_int(uarttxf_int),
		.o_debug(uart_debug)
		// }}}
	);
	// }}}
	// }}}
`else	// BUSCONSOLE_ACCESS
	// {{{
	// Null bus slave
	// {{{

	//
	// In the case that there is no wb32_uart peripheral
	// responding on the wb32 bus
	assign	wb32_uart_ack   = 1'b0;
	assign	wb32_uart_err   = (wb32_uart_stb);
	assign	wb32_uart_stall = 0;
	assign	wb32_uart_idata = 0;

	// }}}
	// Null interrupt definitions
	// {{{
	assign	uartrxf_int = 1'b0;	// uart.INT.UARTRXF.WIRE
	assign	uarttx_int = 1'b0;	// uart.INT.UARTTX.WIRE
	assign	uarttxf_int = 1'b0;	// uart.INT.UARTTXF.WIRE
	assign	uartrx_int = 1'b0;	// uart.INT.UARTRX.WIRE
	// }}}
	// }}}
`endif	// BUSCONSOLE_ACCESS

`ifdef	VERSION_ACCESS
	// {{{
	assign	wb32_version_idata = `DATESTAMP;
	assign	wb32_version_ack = wb32_version_stb;
	assign	wb32_version_stall = 1'b0;
	// }}}
`else	// VERSION_ACCESS
	// {{{
	// }}}
`endif	// VERSION_ACCESS

`ifdef	WBUBUS_MASTER
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	// WBUBUS: USB-UART driven bus master and console
	// {{{
	// The Host USB interface, to be used by the WB-UART bus
	rxuartlite	#(
		// {{{
		.TIMER_BITS(DBGBUSBITS),
		.CLOCKS_PER_BAUD(BUSUART[DBGBUSBITS-1:0])
		// }}}
	) rcv(
		// {{{
		.i_clk(      i_clk),
		.i_uart_rx(i_wbu_uart_rx),
		.o_wr(       wbu_rx_stb),
		.o_data(     wbu_rx_data)
		// }}}
	);

	txuartlite	#(
		// {{{
		.TIMING_BITS(DBGBUSBITS[4:0]),
		.CLOCKS_PER_BAUD(BUSUART[DBGBUSBITS-1:0])
		// }}}
	) txv(
		// {{{
		.i_clk(    i_clk),
		.i_wr(     wbu_tx_stb),
		.i_data(   wbu_tx_data),
		.o_uart_tx(o_wbu_uart_tx),
		.o_busy(   wbu_tx_busy)
		// }}}
	);

`ifndef	BUSPIC_ACCESS
	wire	w_bus_int;
	assign	w_bus_int = 1'b0;
`endif
	// Verilator lint_off UNUSED
	wire	[29:0]	wbu_tmp_addr;
	// Verilator lint_on  UNUSED
	exbuswb #(
		// {{{
		// .LGWATCHDOG(DBGBUSWATCHDOG)
		.ADDRESS_WIDTH(30)
		// }}}
	) genbus(
		// {{{
		.i_clk(i_clk), .i_reset(i_reset),
		.o_reset(ex_reset),
		.i_rx_stb(wbu_rx_stb), .i_rx_byte(wbu_rx_data),
		.o_tx_stb(wbu_tx_stb), .o_tx_byte(wbu_tx_data),
			.i_tx_busy(wbu_tx_busy),
		//
		.i_gpio(2'b00), .o_gpio(ex_gpio),
		//
		.i_console_stb(w_console_tx_stb),
			.i_console_byte(w_console_tx_data),
			.o_console_busy(w_console_busy),
		.o_console_stb(w_console_rx_stb),
			.o_console_byte(w_console_rx_data),
		//
		.o_wb_cyc(wbu_cyc), .o_wb_stb(wbu_stb),
			.o_wb_we(wbu_we),
			.o_wb_addr(wbu_addr),
			.o_wb_data(wbu_data),
			.o_wb_sel(wbu_sel),
		.i_wb_stall(wbu_stall),
			.i_wb_ack(wbu_ack),
		.i_wb_data(wbu_idata),
		.i_wb_err(wbu_err),
		.i_interrupt(w_bus_int)
		// }}}
	);
	// }}}
	// }}}
`else	// WBUBUS_MASTER
	// {{{
	// Null bus master
	// {{{
	// }}}
	// }}}
`endif	// WBUBUS_MASTER

	wbdown #(
		// {{{
		// Slave bus address width: 25
		// Slave address width    : 5
		// Master address width   : 9
		.ADDRESS_WIDTH(5+$clog2(512/8)),
		.WIDE_DW(512),
		.SMALL_DW(32),
		.OPT_LITTLE_ENDIAN(1'b0),
		.OPT_LOWLOGIC(1'b0)
		// }}}
	) u_crossbus (
		// {{{
		.i_clk(i_clk),
		.i_reset(i_reset),
		// Slave/incoming
		// {{{
		.i_wcyc(  wbwide_crossbus_cyc),
		.i_wstb(  wbwide_crossbus_stb),
		.i_wwe(   wbwide_crossbus_we),
		.i_waddr( wbwide_crossbus_addr[5-1:0]),
		.i_wdata( wbwide_crossbus_data),
		.i_wsel(  wbwide_crossbus_sel),
		.o_wstall(wbwide_crossbus_stall),
		.o_wack(  wbwide_crossbus_ack),
		.o_wdata( wbwide_crossbus_idata),
		.o_werr(  wbwide_crossbus_err),
		// }}}
		// Master/down-range/outgoing
		// {{{
		.o_scyc(  wb32_crossbus_cyc),
		.o_sstb(  wb32_crossbus_stb),
		.o_swe(   wb32_crossbus_we),
		.o_saddr( wb32_crossbus_addr[9-1:0]),
		.o_sdata( wb32_crossbus_data),
		.o_ssel(  wb32_crossbus_sel),
		.i_sstall(wb32_crossbus_stall),
		.i_sack(  wb32_crossbus_ack),
		.i_sdata( wb32_crossbus_idata),
		.i_serr(  wb32_crossbus_err)
		// }}}
		// }}}
	);
`ifdef	BUSPIC_ACCESS
	// {{{
	//
	// The BUS Interrupt controller
	//
	icontrol #(15)
	buspici(
		.i_clk(i_clk), .i_reset(1'b0),
		.i_wb_cyc(wb32_buspic_cyc), .i_wb_stb(wb32_buspic_stb), .i_wb_we(wb32_buspic_we),
			.i_wb_data(wb32_buspic_data), // 32 bits wide
			.i_wb_sel(wb32_buspic_sel),  // 32/8 bits wide
		.o_wb_stall(wb32_buspic_stall),.o_wb_ack(wb32_buspic_ack), .o_wb_data(wb32_buspic_idata),
		.i_brd_ints(bus_int_vector),
		.o_interrupt(w_bus_int)
	);
	// }}}
`else	// BUSPIC_ACCESS
	// {{{
	// Null interrupt definitions
	// {{{
	assign	w_bus_int = 1'b0;	// buspic.INT.BUS.WIRE
	// }}}
	// }}}
`endif	// BUSPIC_ACCESS

`ifdef	CFG_ACCESS
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	// ICAPE2 driver/controller
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	//
`ifdef	VERILATOR
	reg	r_cfg_ack;

	initial	r_cfg_ack = 1'b0;
	always @(posedge i_clk)
		r_cfg_ack <= wb32_cfg_stb;
	assign	wb32_cfg_ack   = r_cfg_ack;
	assign	wb32_cfg_stall = 1'b0;
	assign	wb32_cfg_idata = 32'h00;
`else
	wbicapetwo #(
		.LGDIV(ICAPE_LGDIV)
	) cfgport(
		// {{{
		.i_clk(i_clk), .i_reset(i_reset),
		.i_wb_cyc(wb32_cfg_cyc), .i_wb_stb(wb32_cfg_stb), .i_wb_we(wb32_cfg_we),
			.i_wb_addr(wb32_cfg_addr[5-1:0]),
			.i_wb_data(wb32_cfg_data), // 32 bits wide
			.i_wb_sel(wb32_cfg_sel),  // 32/8 bits wide
		.o_wb_stall(wb32_cfg_stall),.o_wb_ack(wb32_cfg_ack), .o_wb_data(wb32_cfg_idata)
		// }}}
	);
`endif
	// }}}
	// }}}
`else	// CFG_ACCESS
	// {{{
	// Null bus slave
	// {{{

	//
	// In the case that there is no wb32_cfg peripheral
	// responding on the wb32 bus
	assign	wb32_cfg_ack   = 1'b0;
	assign	wb32_cfg_err   = (wb32_cfg_stb);
	assign	wb32_cfg_stall = 0;
	assign	wb32_cfg_idata = 0;

	// }}}
	// }}}
`endif	// CFG_ACCESS

	assign	wb32_buildtime_idata = `BUILDTIME;
	assign	wb32_buildtime_ack = wb32_buildtime_stb;
	assign	wb32_buildtime_stall = 1'b0;
`ifdef	PWRCOUNT_ACCESS
	// {{{
	initial	r_pwrcount_data = 32'h0;
	always @(posedge i_clk)
	if (r_pwrcount_data[31])
		r_pwrcount_data[30:0] <= r_pwrcount_data[30:0] + 1'b1;
	else
		r_pwrcount_data[31:0] <= r_pwrcount_data[31:0] + 1'b1;

	assign	wb32_pwrcount_stall = 1'b0;
	assign	wb32_pwrcount_ack   = wb32_pwrcount_stb;
	assign	wb32_pwrcount_idata = r_pwrcount_data;
	// }}}
`else	// PWRCOUNT_ACCESS
	// {{{
	// }}}
`endif	// PWRCOUNT_ACCESS

	////////////////////////////////////////////////////////////////////////
	//
	// RTC Counter
	// {{{
	//
	// Using clock i_clk with frequency 100000000
	//
`ifndef	TIMESYNC
	initial	r_rtccount_data = 32'h0;
	always @(posedge i_clk)
		r_rtccount_data <= r_rtccount_data + 43;

	assign	wb32_rtccount_idata = r_rtccount_data;
`else
	assign	wb32_rtccount_idata = timestamp_100mhz[31:0];
`endif
	// }}}
`ifdef	SPIO_ACCESS
	// {{{
	//
	// Special purpose I/O driver (buttons, LEDs, and switches)
	//
	assign	w_sw = 1'b0;

	spio #(
		.NBTN(2), .NLEDS(8), .NSW(1)
	) spioi(
		.i_clk(i_clk), .i_reset(i_reset),
		.i_wb_cyc(wb32_spio_cyc), .i_wb_stb(wb32_spio_stb), .i_wb_we(wb32_spio_we),
			.i_wb_data(wb32_spio_data), // 32 bits wide
			.i_wb_sel(wb32_spio_sel),  // 32/8 bits wide
		.o_wb_stall(wb32_spio_stall),.o_wb_ack(wb32_spio_ack), .o_wb_data(wb32_spio_idata),
		.i_sw(w_sw), .i_btn(i_btn), .o_led(w_led),
		.o_int(spio_int)
	);

	assign	o_led = ~w_led;

	// }}}
`else	// SPIO_ACCESS
	// {{{
	assign	o_led = -1;
	// Null interrupt definitions
	// {{{
	assign	spio_int = 1'b0;	// spio.INT.SPIO.WIRE
	// }}}
	// }}}
`endif	// SPIO_ACCESS

	////////////////////////////////////////////////////////////////////////
	//
	// WBUBUS "wbu_arbiter" master->slave connection
	// {{{

	wbupsz #(
		// {{{
		// Slave bus address width : 30
		// Slave address width     : 29
		// Master bus address width: 25
		.ADDRESS_WIDTH(25+$clog2(512/8)),
		.SMALL_DW(32),
		.WIDE_DW(512),
		.OPT_LITTLE_ENDIAN(1'b0)
		// }}}
	) u_wbu_wbwide_downsz (
		// {{{
		.i_clk(i_clk),
		.i_reset(i_reset),
		.i_scyc(wbu_wbu_arbiter_cyc), .i_sstb(wbu_wbu_arbiter_stb), .i_swe(wbu_wbu_arbiter_we),
			.i_saddr(wbu_wbu_arbiter_addr[29-1:0]),
			.i_sdata(wbu_wbu_arbiter_data), // 32 bits wide
			.i_ssel(wbu_wbu_arbiter_sel),  // 32/8 bits wide
		.o_sstall(wbu_wbu_arbiter_stall),.o_sack(wbu_wbu_arbiter_ack), .o_sdata(wbu_wbu_arbiter_idata), .o_serr(wbu_wbu_arbiter_err),
		.o_wcyc(wbwide_wbu_arbiter_cyc), .o_wstb(wbwide_wbu_arbiter_stb), .o_wwe(wbwide_wbu_arbiter_we),
			.o_waddr(wbwide_wbu_arbiter_addr[25-1:0]),
			.o_wdata(wbwide_wbu_arbiter_data), // 512 bits wide
			.o_wsel(wbwide_wbu_arbiter_sel),  // 512/8 bits wide
		.i_wstall(wbwide_wbu_arbiter_stall), .i_wack(wbwide_wbu_arbiter_ack), .i_wdata(wbwide_wbu_arbiter_idata), .i_werr(wbwide_wbu_arbiter_err)
		// }}}
	);

	// }}}
	// }}}
endmodule // main.v
